export const uiFallbackText: Record<string, string> = {
  'nav.home': 'Trang chủ',
  'nav.quick_search': 'Tìm kiếm nhanh',
  'nav.open_breadcrumb': 'Mở đường dẫn breadcrumb',
  'nav.overview': 'Tổng quan',
  'nav.events': 'Sự kiện',
  'nav.dashboard': 'Bảng điều khiển',
  'nav.venues': 'Địa điểm',
  'nav.transactions': 'Giao dịch',
  'nav.users': 'Người dùng',
  'nav.system': 'Hệ thống',
  'nav.tasks': 'Tác vụ',
  'nav.waiting_room': 'Phòng chờ',
  'nav.feature_flags': 'Cờ tính năng',
  'common.admin': 'Quản trị',
  'common.back': 'Quay lại',
  'common.optional': 'Tùy chọn',
  'common.edit': 'Chỉnh sửa',
  'common.not_set': 'Chưa thiết lập',
  'admin.transactions.order_id': 'Mã đơn hàng',
  'admin.transactions.buyer_info': 'Thông tin người mua',
  'admin.transactions.seat_info': 'Thông tin ghế',
  'admin.transactions.total_amount': 'Tổng tiền',
  'admin.transactions.payment_time': 'Thời gian thanh toán',
  'admin.transactions.status': 'Trạng thái giao dịch',
  'admin.transactions.no_buyer_name': 'Chưa có tên',
  'admin.transactions.no_buyer_email': 'Chưa có email',
  'admin.transactions.no_seats': 'Không có ghế',
  'admin.transactions.unpaid': 'Chưa thanh toán',
  'admin.transactions.load_failed': 'Không thể tải danh sách giao dịch',
  'admin.transactions.status_confirmed': 'Đã xác nhận',
  'admin.transactions.status_pending': 'Đang chờ',
  'admin.transactions.status_cancelled': 'Đã hủy',
  'admin.transactions.status_expired': 'Đã hết hạn',
  'admin.tasks.title': 'Tác vụ nền',
  'admin.tasks.desc': 'Kích hoạt thủ công các tác vụ hệ thống không thể chạy theo lịch trong môi trường sản xuất.',
  'admin.tasks.run': 'Chạy tác vụ',
  'admin.tasks.running': 'Đang chạy...',
  'admin.tasks.success': 'Thành công',
  'admin.tasks.failed': 'Thất bại',
  'admin.tasks.at': 'lúc',
  'admin.tasks.release_holds_title': 'Giải phóng chỗ giữ hết hạn',
  'admin.tasks.release_holds_desc': 'Giải phóng ghế từ bộ hẹn giờ giữ chỗ hết hạn và tính toán lại phân tích cho tất cả sự kiện.',
  'admin.tasks.admit_queue_title': 'Vào nhóm hàng đợi',
  'admin.tasks.admit_queue_desc': 'Xử lý nhóm vào cửa tiếp theo cho tất cả sự kiện có hàng đợi và xóa các mục cũ.',
  'admin.tasks.seed_admin_title': 'Tạo tài khoản quản trị',
  'admin.tasks.seed_admin_desc': 'Tạo tài khoản quản trị viên mặc định nếu chưa tồn tại.',
  'admin.tasks.reseed_events_title': 'Tạo lại sự kiện demo',
  'admin.tasks.reseed_events_desc': 'Xóa dữ liệu sự kiện hiện tại và tạo lại 10 sự kiện demo với 10 địa điểm riêng ở Hà Nội và Hồ Chí Minh.',
  'admin.tasks.completed': '{title} đã hoàn thành',
  'admin.tasks.task_failed': '{title} thất bại: {message}',
  'admin.tasks.result_release_holds_done': 'Đã giải phóng {count} vé giữ quá hạn.',
  'admin.tasks.result_admit_queue_done': 'Đã cho {count} người trong hàng chờ vào mua vé.',
  'admin.tasks.result_seed_admin_ready': 'Tài khoản quản trị {username} đã sẵn sàng.',
  'admin.tasks.result_seed_admin_checked': 'Đã kiểm tra tài khoản {username}.',
  'admin.tasks.result_reseed_events_done': 'Đã tạo lại {count} sự kiện mẫu.',
  'admin.tasks.result_release_holds_empty': 'Không có vé giữ quá hạn cần giải phóng.',
  'admin.tasks.result_admit_queue_empty': 'Chưa có người mới được đưa từ hàng chờ vào.',
  'admin.tasks.result_completed': 'Tác vụ đã hoàn tất.',
  'admin.tasks.metric_released_tickets': 'Vé đã nhả',
  'admin.tasks.metric_events_updated': 'Sự kiện cập nhật',
  'admin.tasks.metric_admitted': 'Người được vào',
  'admin.tasks.metric_changed_sessions': 'Phiên có thay đổi',
  'admin.tasks.metric_expired_holds': 'Hold hết hạn',
  'admin.tasks.metric_account': 'Tài khoản',
  'admin.tasks.metric_display_name': 'Tên hiển thị',
  'admin.tasks.metric_admin_role': 'Quyền admin',
  'admin.tasks.metric_created_events': 'Sự kiện tạo mới',
  'admin.tasks.metric_venues': 'Địa điểm',
  'admin.tasks.metric_cities': 'Thành phố',
  'admin.tasks.enabled': 'Đã bật',
  'admin.tasks.disabled': 'Chưa bật',
  'admin.tasks.technical_details': 'Chi tiết kỹ thuật',
  'admin.event_create.page_title': 'Tạo sự kiện',
  'admin.event_create.breadcrumb': 'Tạo sự kiện',
}

export function getUiFallbackText(key: string) {
  return uiFallbackText[key] ?? key
}
